# Generated by Django 6.0.5 on 2026-05-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_warehouse',
            field=models.BooleanField(default=False, verbose_name='Сотрудник склада'),
        ),
    ]
