# Generated by Django 6.0.5 on 2026-05-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_user_is_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_editor',
            field=models.BooleanField(default=False, verbose_name='Редактор сайта'),
        ),
    ]
